spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mycosts_db}
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema:classpath: session_tables.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow

  mail:
    host: smtp.gmail.com
    username: mycostssender@gmail.com
    password: mycosts12345
    port: 465
    protocol: smtps

mail:
  debug: true

security:
  oauth2:
    client:
      clientId: 943545081954-55rlcab13b8r6m9tqpgsak61rcp8edop.apps.googleusercontent.com
      clientSecret: VwEySXDOatnI41PMe35mGmYF
      clientAuthenticationScheme: form
      scope: openid,email,profile
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      preferTokenInfo: true
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
server:
  port: ${PORT:8080}

